### ISSUE TITLE
Date problem

### ISSUE THREAD

**Issue by Thanh-8213** [etc5521-2020/assignment-1-cassowary#1]
There are some lines of data that is recorded with wrong date (01-01-1970). Therefore, I filtered them out and keep only data with date from 2018 onward. 

Evidence: 
![image](https://user-images.githubusercontent.com/64292246/90505482-0b59cd00-e196-11ea-8faf-23d8a36647ea.png)

**Comment by TengMCing** [comment]
Cool, I clean up the scraping code a little bit and upload the data, would you like to merge your branch to the master branch. By the way, we don't need to have another Rmd file besides `index.Rmd`. Other than that, we will not use the data they scraped in April, I already set up the scraping action in `index.Rmd` which will collect the latest data. You can bring your analysis to the index.Rmd based on the local dataset.

**Comment by Thanh-8213** [comment]
Nice to hear from you, Weihao
Did you do data description?

**Comment by Thanh-8213** [comment]
I wrote the data description with their timeframe. If we want to use the
latest data, I suggest we ask the tutors first.
