### ISSUE TITLE
Making a map in question 1

### ISSUE THREAD

**Issue by Thanh-8213** [etc5521-2020/assignment-1-cassowary#4]
![image](https://user-images.githubusercontent.com/64292246/91520572-f10fb400-e938-11ea-8525-0c9530d91ebb.png)

Instead of this bar chart, do you think a map is better? If we have time, I think we can do it

**Comment by TengMCing** [comment]
I actually did a map before, but it didn't stand up so I delete it and replace it with this bar chart, let me redo it and show it to you. Let's see which will be better.
